export type AdminLocale = "de" | "ar";

const DE: Record<string, string> = {
  "shell.loading": "Laden…",
  "shell.redirectLogin": "Weiterleitung zur Anmeldung…",
  "shell.headerTitle": "TransPool24 – Admin",
  "shell.logout": "Abmelden",
  "shell.lang.de": "DE",
  "shell.lang.ar": "AR",
  "shell.lang.title": "Sprache",
  "shell.footerSecurity":
    "Geschützte Admin-Sitzung · HttpOnly-Cookie · Sicherheits-Header (Frame, MIME, Referrer)",
  "shell.footerDeploy": "Deployment: {env} · Commit {sha}",
  "shell.footerDeployLocal": "Lokal / Vorschau — keine Vercel-Metadaten",
  "shell.footerVercelDeployment": "Aktuelle Vercel-Host-URL (Vorschau)",
  "shell.footerRateLimit": "Öffentliche API: Begrenzung {mode} (pro Instanz; RATE_LIMIT_DISABLED=1 schaltet ab)",
  "shell.footerCronOn": "Cron Auftrags-Erinnerung: CRON_SECRET gesetzt",
  "shell.footerCronOff": "Cron Auftrags-Erinnerung: CRON_SECRET fehlt",
  "shell.footerCookieBanner":
    "Öffentliche Website: Cookie-Einwilligung erzwungen bis zur Auswahl (v1, localStorage).",
  "shell.footerLegal":
    "Öffentliche Seiten: /privacy & /terms (alle Sprachen, Sitemap).",
  "shell.footerSeoIntro": "SEO & Indexierung:",
  "shell.footerSeoSite": "Öffentliche Site",
  "shell.footerSeoSitemap": "Sitemap",
  "shell.footerSeoRobots": "Robots",
  "shell.footerSeoGsc": "Google: Meta-Verifizierung im Root-Layout.",
  "nav.unread": "ungelesen",
  "nav.orders": "Aufträge",
  "nav.reports": "Berichte",
  "nav.driverApplications": "Fahrerbewerbungen",
  "nav.drivers": "Fahrer",
  "nav.blog": "Blog / Magazin",
  "nav.settings": "Einstellungen",
  "nav.support": "Support-Nachrichten",
  "nav.ratings": "Bewertungen",
  "ratings.title": "Kundenbewertungen (Fahrer)",
  "ratings.subtitle":
    "Sterne und Kommentare von der Seite „Fahrer bewerten“. Nur aktivierte Einträge erscheinen zusätzlich im Homepage-Karussell.",
  "ratings.loading": "Laden…",
  "ratings.none": "Noch keine Bewertungen.",
  "ratings.dbHint":
    "Spalten fehlen? In Supabase SQL Editor: supabase/publish_customer_driver_reviews.sql ausführen.",
  "ratings.colOrder": "Auftrag",
  "ratings.colCompany": "Firma",
  "ratings.colDriver": "Fahrer",
  "ratings.colStars": "Sterne",
  "ratings.colComment": "Kommentar",
  "ratings.colSite": "Startseite",
  "ratings.siteOn": "Sichtbar",
  "ratings.siteOff": "Aus",
  "ratings.openOrder": "Auftrag",
  "ratings.toggleError": "Speichern fehlgeschlagen",
  "orders.title": "Aufträge",
  "orders.exportCsv": "CSV exportieren",
  "orders.jumpToOps": "In Bearbeitung & geliefert (Fotos) — nach unten",
  "orders.searchPlaceholder":
    "Suche: Auftragsnr., Firma, E-Mail, Adresse, Status …",
  "orders.filterAllStatus": "Alle Status",
  "orders.loading": "Laden…",
  "orders.colNr": "Nr.",
  "orders.colStatus": "Status",
  "orders.colDate": "Datum",
  "orders.colCompany": "Firma",
  "orders.colService": "Leistung",
  "orders.colCustomerEur": "Kunde €",
  "orders.colDriverEur": "Fahrer €",
  "orders.colAssistantEur": "Helfer €",
  "orders.colPayment": "Zahlung",
  "orders.colActions": "Aktionen",
  "orders.openFile": "Öffnen",
  "orders.deleteAria": "Auftrag endgültig löschen",
  "orders.deleteConfirm":
    "Auftrag {order} endgültig aus dem System löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
  "orders.deleteFailed": "Löschen fehlgeschlagen",
  "orders.paymentPaid": "Bezahlt",
  "orders.paymentPending": "Ausstehend",
  "orders.priceTitle": "Kundenpreis (berechnet nach Service-Typ bei Zahlung)",
  "orders.assistantTitle": "Vergütung Helfer (Fahrer + Helfer)",
  "orders.opsIntro":
    "Operations-Board — unter der Tabelle: aktive Aufträge, dann gelieferte mit Liefernachweis-Fotos.",
  "orders.noOrders":
    "Keine Aufträge im System (Verbindung oder API-Berechtigung prüfen).",
  "orders.inProgressTitle": "Aktive Aufträge",
  "orders.inProgressDesc":
    "Bestätigt oder in Zustellung (bestätigt, bezahlt, zugewiesen, unterwegs). Tracking und ETA nur hier.",
  "orders.noInProgress": "Derzeit keine Aufträge in Bearbeitung.",
  "orders.dtCompany": "Firma",
  "orders.dtService": "Leistung",
  "orders.dtCustomerEur": "Kunde €",
  "orders.dtDriverEur": "Fahrer €",
  "orders.dtPayment": "Zahlung",
  "orders.dtDistance": "Entfernung",
  "orders.dtDuration": "Routendauer (Min.)",
  "orders.dtEtaMin": "Restminuten (ETA)",
  "orders.dtEta": "Voraussichtliche Ankunft",
  "orders.dtLastGps": "Letzte GPS-Position",
  "orders.dtPickup": "Abholung",
  "orders.dtDelivery": "Zustellung",
  "orders.deliveredTitle": "Geliefert — Liefernachweis (Foto)",
  "orders.deliveredDesc":
    "Aufträge mit Status „geliefert“ und Liefernachweis-Foto (vom Fahrer über GPS-Link).",
  "orders.noDeliveredTitle": "Noch keine Aufträge mit Status „geliefert“.",
  "orders.noDeliveredDesc":
    "Wenn der Fahrer ein Foto über den GPS-Link hochlädt oder Sie den Status manuell auf „geliefert“ setzen, erscheint der Auftrag hier mit Bildvorschau. Button „Lieferbestätigung per E-Mail“ sendet eine deutschsprachige Bestätigung an den Kunden inkl. Foto-Link falls vorhanden.",
  "orders.deliveredBadge": "Geliefert",
  "orders.podAt": "Bestätigt:",
  "orders.podPhoto": "Liefernachweis-Foto",
  "orders.podAlt": "Liefernachweis",
  "orders.podNoPhoto":
    "Kein Foto — Link kann in der Auftragsakte manuell gesetzt werden.",
  "orders.emailNoCustomer": "Keine Kunden-E-Mail für diesen Auftrag.",
  "orders.emailTitle":
    "E-Mail an Kunden (DE): Lieferbestätigung + Foto falls vorhanden",
  "orders.emailSending": "Wird gesendet…",
  "orders.emailBtn": "Lieferbestätigung per E-Mail",
  "orders.emailHint": "Kunden-E-Mail in der Auftragsakte eintragen",
  "orders.alertNoEmail": "Keine Kunden-E-Mail für diesen Auftrag.",
  "orders.alertFail": "Senden fehlgeschlagen",
  "orders.alertSent": "Lieferbestätigung gesendet an:",
  "orders.alertNetwork": "Netzwerkfehler",
  "orders.noneFiltered": "Keine Aufträge.",
  "orders.statusPick": "Status wählen",
  "orders.statusAria": "Status",
  "service.driver_only": "Nur Fahrer",
  "service.driver_car": "Fahrer mit Fahrzeug",
  "service.driver_car_assistant": "Fahrer mit Fahrzeug + Helfer",
};

const AR: Record<string, string> = {
  "shell.loading": "جاري التحميل…",
  "shell.redirectLogin": "إعادة التوجيه لتسجيل الدخول…",
  "shell.headerTitle": "TransPool24 – الإدارة",
  "shell.logout": "تسجيل الخروج",
  "shell.lang.de": "DE",
  "shell.lang.ar": "عربي",
  "shell.lang.title": "اللغة",
  "shell.footerSecurity":
    "جلسة إدارة محمية · كوكي HttpOnly · رؤوس أمان (إطار، MIME، Referrer)",
  "shell.footerDeploy": "النشر: {env} · الالتزام {sha}",
  "shell.footerDeployLocal": "محلي / معاينة — لا بيانات Vercel",
  "shell.footerVercelDeployment": "رابط استضافة Vercel الحالي (معاينة)",
  "shell.footerRateLimit": "واجهة عامة: حد الطلبات {mode} (لكل instance؛ RATE_LIMIT_DISABLED=1 يعطّل)",
  "shell.footerCronOn": "جدولة تذكير الطلبات: CRON_SECRET مضبوط",
  "shell.footerCronOff": "جدولة تذكير الطلبات: لا يوجد CRON_SECRET",
  "shell.footerCookieBanner":
    "الموقع العام: بانر موافقة الكوكيز إجباري حتى الاختيار (v1، localStorage).",
  "shell.footerLegal":
    "صفحات عامة: /privacy و /terms (كل اللغات، خريطة الموقع).",
  "shell.footerSeoIntro": "SEO والفهرسة:",
  "shell.footerSeoSite": "الموقع العام",
  "shell.footerSeoSitemap": "خريطة الموقع",
  "shell.footerSeoRobots": "Robots",
  "shell.footerSeoGsc": "Google: التحقق عبر وسم ميتا في الجذر.",
  "nav.unread": "غير مقروء",
  "nav.orders": "طلبات",
  "nav.reports": "التقارير",
  "nav.driverApplications": "تطبيقات السائقين",
  "nav.drivers": "سائق",
  "nav.blog": "مدونة / مجلة",
  "nav.settings": "إعدادات",
  "nav.support": "رسائل الدعم",
  "nav.ratings": "تقييمات",
  "ratings.title": "تقييمات العملاء (السائق)",
  "ratings.subtitle":
    "النجوم والتعليقات من صفحة «تقييم السائق». ما يُفعّل فقط يظهر أيضاً في شريط آراء العملاء بالصفحة الرئيسية.",
  "ratings.loading": "جاري التحميل…",
  "ratings.none": "لا توجد تقييمات بعد.",
  "ratings.dbHint":
    "أعمدة ناقصة؟ نفّذ في Supabase: supabase/publish_customer_driver_reviews.sql",
  "ratings.colOrder": "الطلب",
  "ratings.colCompany": "الشركة",
  "ratings.colDriver": "السائق",
  "ratings.colStars": "النجوم",
  "ratings.colComment": "التعليق",
  "ratings.colSite": "الموقع",
  "ratings.siteOn": "ظاهر",
  "ratings.siteOff": "مخفي",
  "ratings.openOrder": "فتح الطلب",
  "ratings.toggleError": "فشل الحفظ",
  "orders.title": "طلبات",
  "orders.exportCsv": "تصدير CSV",
  "orders.jumpToOps": "قيد التنفيذ وتم التوصيل (صور) — انتقل للأسفل",
  "orders.searchPlaceholder":
    "بحث: رقم الطلب، شركة، بريد، عنوان، حالة …",
  "orders.filterAllStatus": "جميع الحالات",
  "orders.loading": "جاري التحميل…",
  "orders.colNr": "رقم",
  "orders.colStatus": "الحالة",
  "orders.colDate": "التاريخ",
  "orders.colCompany": "الشركة",
  "orders.colService": "طلب شركة",
  "orders.colCustomerEur": "العميل €",
  "orders.colDriverEur": "السائق €",
  "orders.colAssistantEur": "معاون €",
  "orders.colPayment": "الدفع",
  "orders.colActions": "إجراءات",
  "orders.openFile": "فتح ملف",
  "orders.deleteAria": "حذف الطلب نهائياً",
  "orders.deleteConfirm":
    "حذف الطلب {order} نهائياً من النظام؟ لا يمكن التراجع عن هذا الإجراء.",
  "orders.deleteFailed": "فشل الحذف",
  "orders.paymentPaid": "مدفوع",
  "orders.paymentPending": "قيد الانتظار",
  "orders.priceTitle": "سعر العميل (يُحسب عند الدفع حسب نوع الخدمة)",
  "orders.assistantTitle": "أجر المعاون (شوفير + معاون)",
  "orders.opsIntro":
    "لوحة التشغيل — تظهر دائماً تحت الجدول: الطلبات النشطة ثم المُسلَّمة مع صور الإثبات.",
  "orders.noOrders":
    "لا توجد طلبات في النظام (تحقق من الاتصال أو صلاحيات API).",
  "orders.inProgressTitle": "تنفيذ الطلبات — قيد التنفيذ",
  "orders.inProgressDesc":
    "طلبات مؤكدة أو مسار التوصيل (مؤكد، مدفوع، مُعيَّن، في الطريق). تفاصيل التتبع ووقت الوصول المتوقع هنا فقط.",
  "orders.noInProgress": "لا توجد طلبات قيد التنفيذ حالياً.",
  "orders.dtCompany": "الشركة",
  "orders.dtService": "نوع الخدمة",
  "orders.dtCustomerEur": "العميل €",
  "orders.dtDriverEur": "السائق €",
  "orders.dtPayment": "الدفع",
  "orders.dtDistance": "المسافة",
  "orders.dtDuration": "مدة التوجيه (دقيقة)",
  "orders.dtEtaMin": "دقائق متبقية (ETA)",
  "orders.dtEta": "وصول متوقع",
  "orders.dtLastGps": "آخر موقع GPS",
  "orders.dtPickup": "الاستلام",
  "orders.dtDelivery": "التسليم",
  "orders.deliveredTitle": "تم التوصيل — إثبات التسليم (صورة)",
  "orders.deliveredDesc":
    "الطلبات بحالة «تم التوصيل» مع صورة إثبات يرفعها السائق من رابط GPS.",
  "orders.noDeliveredTitle": "لا توجد طلبات بحالة «تم التوصيل» بعد.",
  "orders.noDeliveredDesc":
    "عندما يرفع السائق صورة التسليم من رابط GPS، أو عندما تضعون الحالة «تم التوصيل» يدوياً، يظهر الطلب هنا مع معاينة الصورة. استخدموا زر «إيميل تأكيد التسليم» لإرسال تأكيد للعميل (بالألمانية) مع رابط الصورة إن وُجدت.",
  "orders.deliveredBadge": "تم التوصيل",
  "orders.podAt": "تأكيد:",
  "orders.podPhoto": "صورة إثبات التسليم",
  "orders.podAlt": "إثبات التسليم",
  "orders.podNoPhoto":
    "لا توجد صورة مرفوعة — يمكن إضافة رابط يدوياً من ملف الطلب.",
  "orders.emailNoCustomer": "لا يوجد بريد للعميل على هذا الطلب.",
  "orders.emailTitle":
    "إرسال إيميل للعميل (ألماني): تأكيد التسليم + صورة إن وُجدت",
  "orders.emailSending": "جاري الإرسال…",
  "orders.emailBtn": "إيميل تأكيد التسليم للعميل",
  "orders.emailHint": "أضف بريد العميل من ملف الطلب",
  "orders.alertNoEmail": "لا يوجد بريد إلكتروني للعميل على هذا الطلب.",
  "orders.alertFail": "فشل الإرسال",
  "orders.alertSent": "تم إرسال تأكيد التسليم إلى:",
  "orders.alertNetwork": "خطأ في الشبكة",
  "orders.noneFiltered": "لا توجد طلبات.",
  "orders.statusPick": "اختر الحالة",
  "orders.statusAria": "الحالة",
  "service.driver_only": "شوفير من دون سيارة",
  "service.driver_car": "شوفير مع سيارة",
  "service.driver_car_assistant": "شوفير مع سيارة ومعاون",
};

const MAP: Record<AdminLocale, Record<string, string>> = { de: DE, ar: AR };

export function adminT(locale: AdminLocale, key: string): string {
  return MAP[locale][key] ?? MAP.de[key] ?? key;
}

export function serviceTypeLabel(locale: AdminLocale, st: string | undefined): string {
  if (st === "driver_only") return adminT(locale, "service.driver_only");
  if (st === "driver_car_assistant") return adminT(locale, "service.driver_car_assistant");
  return adminT(locale, "service.driver_car");
}
