-- why_transpool24_locale: rows with payload.contentRevision < WHY_PAGE_CONTENT_REVISION (see
-- src/lib/why-transpool24-types.ts) are IGNORED at runtime — the app uses code defaults instead.
-- Manual DELETE is optional; bump WHY_PAGE_CONTENT_REVISION when shipping a new default copy.
--
-- Optional reset (forces one DB row to disappear; next save from CMS re-creates it):
-- DELETE FROM why_transpool24_locale;
-- DELETE FROM why_transpool24_locale WHERE locale = 'ar';
