-- why_transpool24_locale OVERRIDES code defaults in src/lib/why-defaults-*.ts
-- If /ar/why (or any locale) still shows old copy (furniture, fragile goods, vehicle moves),
-- remove the stored row so the site uses the new B2B defaults from the repo.
--
-- Option A — Website CMS: /website/why → language "ar" → button "Code-Standard" (calls DELETE API).
--
-- Option B — Supabase SQL Editor (all locales):
-- DELETE FROM why_transpool24_locale;
--
-- Option B — Arabic only:
-- DELETE FROM why_transpool24_locale WHERE locale = 'ar';
